class_name: Sequential
config:
  name: sequential
  layers:
    - class_name: InputLayer
      config:
        batch_input_shape: [null, 28, 28, 1]
        dtype: float32
        name: input_1
    - class_name: Conv2D
      config:
        filters: 32
        kernel_size: [3, 3]
        activation: relu
        name: conv2d
    - class_name: MaxPooling2D
      config:
        pool_size: [2, 2]
        name: max_pooling2d
    - class_name: Conv2D
      config:
        filters: 64
        kernel_size: [3, 3]
        activation: relu
        name: conv2d_1
    - class_name: MaxPooling2D
      config:
        pool_size: [2, 2]
        name: max_pooling2d_1
    - class_name: Flatten
      config:
        name: flatten
    - class_name: Dropout
      config:
        rate: 0.5
        name: dropout
    - class_name: Dense
      config:
        units: 10
        activation: softmax
        name: dense
keras_version: '3.3.3'
backend: tensorflow