artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  tf_dataset: mnist
  local_data_folder: artifacts/data_ingestion
  

# data_validation:
#   root_dir: artifacts/data_validation
#   STATUS_FILE: artifacts/data_validation/status.txt
#   ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  data_path: artifacts/data_ingestion
  tf_dataset: mnist
  max_pixel_intensity: 255
  batch_size: 128


model_trainer:
  root_dir: artifacts/model_trainers
  saved_trained_model: trained_model.h5
  architecture_config_dir: source/model_config/architecture_config.yaml
  compilation_config_dir: source/model_config/compilation_config.yaml


model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainers/trained_model.h5
  metric_file_name: artifacts/model_evaluation/metrics.csv

model_registration:
  model_path: artifacts/model_trainers/trained_model.h5
  model_registry_folder: model_registry
  registered_model_name: mnist_classifier

